"""add signup fields to users

Revision ID: 503544b10945
Revises: 001_initial
Create Date: 2025-06-06 11:47:17.911985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '503544b10945'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employment_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('primary_interests', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('how_did_you_hear', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'how_did_you_hear')
    op.drop_column('users', 'primary_interests')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'current_role')
    op.drop_column('users', 'employment_status')
    # ### end Alembic commands ###
